### PR TITLE
Fixed dtype error in KMeans clustering

### PR DESCRIPTION
**Pull request by rafaljanwojcik**
Please check if with this fix everything is working for you, if yes, I will merge branches

### CODE REVIEW

**Comment by AndromRyan** [comment]
#5 I believe this has fixed the issue. Getting through to the next stages of the repo

**Comment by senanabs** [comment]
Hello,

The issue is resolved for me now. Thank you very much for looking into this. 

I applied your method to a dataset I have. Although accuracy for the validation is 83%, precision is fairly low at 7.5%. Recall and f1 are also low (less than 10%). I am looking into why this is. Any input from you would be appreciated. Thanks

**Comment by rafaljanwojcik** [comment]
Great I will merge it then. Main problem might be that this technique is very simple, and for more complicated datasets (more complicated reviews) it doesn't perform well - for my dataset, the reviews were very short and actually contained only words that indicate positive or negative sentiment. On the other hand for datasets with more complicated reviews, were not all words are sentiment-related (there are not only words like 'I liked it', 'Good quality', 'Long delivery, not satisfied'),  but long reviews, it might be too simple. 

There are other techniques of unsupervised cluster refinement that can be leveraged (i.e. https://arxiv.org/abs/1911.08891) to achieve better performance, along with pre-trained language models (i.e. BERT) that can serve as better encoders of sentences than simple Word2Vec algorithm, I encourage you to look into it if you find this technique too simple for your dataset. See also this discussion https://github.com/rafaljanwojcik/Unsupervised-Sentiment-Analysis/issues/4 for options of supervised training models with little amount of labeled data

**Comment by senanabs** [comment]
Thank you @rafaljanwojcik.  I will look into those resources.

**Pull request merged**
